"""Adiciona file_data e remove file_path de Dataset

Revision ID: 733e3dd5da86
Revises: b04ec342c26c
Create Date: 2025-11-30 21:36:10.785304

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '733e3dd5da86'
down_revision = 'b04ec342c26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', postgresql.BYTEA(), nullable=True))
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
