"""Adiciona coluna target_variable para MLModel

Revision ID: d9b4b4623b74
Revises: b406deaf7a33
Create Date: 2025-11-15 00:01:51.382053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9b4b4623b74'
down_revision = 'b406deaf7a33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model', schema=None) as batch_op:
        batch_op.alter_column('target_variable',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model', schema=None) as batch_op:
        batch_op.alter_column('target_variable',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
